POST http://localhost:3000/api/offers
Content-Type: application/json

{
    "title": "Super fast boat",
    "mobile": "697347851",
    "category": "sale",
    "description": "New boat",
    "location": "Szczecin/PL",
    "price": 23000
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "test@gmail.com",
    "fullName": "Test" ,
    "password": "123123321"
}

###
GET http://localhost:3000/api/offers/paginate

###
GET http://localhost:3000/api/products

### 
POST http://localhost:3000/api/checkout
Content-Type: application/json

{
    "id": "recFneDOh4xaWZV67",
    "offerId": 1,
    "quantity": 1
}

###
POST http://localhost:3000/api/users/resetPassword
Content-Type: application/json

{
    "email": "admin@example.com"
}

###
PUT http://localhost:3000/api/users/resetPassword
Content-Type: application/json

{
    "resetToken": "beccaf03255073d8d2f41a99c4b6d2628ce07a0f897fc405992f916d14b6fddc",
    "password": "admin"
}

###
POST http://localhost:3000/api/offers/23/view
Content-Type: application/json

{
    "id": "recLldOm9heM30SkM"
}

###
GET https://api.airtable.com/v0/appH5H2AN227pudOr/offers?filterByFormula=idFromFavUser%3D7&api_key=keyhYJ1oaVeWK1TXF
